[2025-02-13T19:42:47.859+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: download_dataset.download_dataset manual__2025-02-13T19:42:47.384317+00:00 [queued]>
[2025-02-13T19:42:47.867+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: download_dataset.download_dataset manual__2025-02-13T19:42:47.384317+00:00 [queued]>
[2025-02-13T19:42:47.868+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-02-13T19:42:47.881+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): download_dataset> on 2025-02-13 19:42:47.384317+00:00
[2025-02-13T19:42:47.887+0000] {standard_task_runner.py:57} INFO - Started process 1844 to run task
[2025-02-13T19:42:47.890+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'download_dataset', 'download_dataset', 'manual__2025-02-13T19:42:47.384317+00:00', '--job-id', '64', '--raw', '--subdir', 'DAGS_FOLDER/download_dataset_dag.py', '--cfg-path', '/tmp/tmpk0v88_24']
[2025-02-13T19:42:47.891+0000] {standard_task_runner.py:85} INFO - Job 64: Subtask download_dataset
[2025-02-13T19:42:47.940+0000] {task_command.py:416} INFO - Running <TaskInstance: download_dataset.download_dataset manual__2025-02-13T19:42:47.384317+00:00 [running]> on host f09fff4ef036
[2025-02-13T19:42:48.019+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='download_dataset' AIRFLOW_CTX_TASK_ID='download_dataset' AIRFLOW_CTX_EXECUTION_DATE='2025-02-13T19:42:47.384317+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-13T19:42:47.384317+00:00'
[2025-02-13T19:42:48.020+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-02-13T19:42:48.021+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'kaggle datasets download -d blastchar/telco-customer-churn -p /opt/***/basic-pipeline --unzip']
[2025-02-13T19:42:48.037+0000] {subprocess.py:86} INFO - Output:
[2025-02-13T19:42:49.105+0000] {subprocess.py:93} INFO - Warning: Your Kaggle API key is readable by other users on this system! To fix this, you can run 'chmod 600 /home/***/.kaggle/kaggle.json'
[2025-02-13T19:42:49.105+0000] {subprocess.py:93} INFO - Dataset URL: https://www.kaggle.com/datasets/blastchar/telco-customer-churn
[2025-02-13T19:42:49.105+0000] {subprocess.py:93} INFO - License(s): copyright-authors
[2025-02-13T19:42:49.105+0000] {subprocess.py:93} INFO - Downloading telco-customer-churn.zip to /opt/***/basic-pipeline
[2025-02-13T19:42:49.118+0000] {subprocess.py:93} INFO -   0%|          | 0.00/172k [00:00<?, ?B/s]100%|██████████| 172k/172k [00:00<00:00, 31.7MB/s]
[2025-02-13T19:42:49.119+0000] {subprocess.py:93} INFO - 
[2025-02-13T19:42:49.153+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-02-13T19:42:49.184+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=download_dataset, task_id=download_dataset, execution_date=20250213T194247, start_date=20250213T194247, end_date=20250213T194249
[2025-02-13T19:42:49.227+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-02-13T19:42:49.259+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
